name: Code coverage Py

on:
  push:
    branches: [ "dev" , "feature/01-calculation_pro"]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup Python Version
        uses: actions/setup-python@2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Rub tests
        run: pytest
      
      - name: Run code coverage
        run: coverage report -m